/** @type {import('tailwindcss').Config} */
const token = (name) => `rgb(var(--${name}) / <alpha-value>)`

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Manrope', 'ui-sans-serif', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
        display: ['Unbounded', 'Manrope', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
      colors: {
        bg: token('bg'),
        surface: token('surface'),
        'surface-2': token('surface-2'),
        ink: token('ink'),
        muted: token('muted'),
        faint: token('faint'),
        line: token('line'),
        accent: { DEFAULT: token('accent'), soft: token('accent-soft'), ink: token('accent-ink') },
        good: { DEFAULT: token('good'), soft: token('good-soft') },
        bad: { DEFAULT: token('bad'), soft: token('bad-soft') },
        warn: { DEFAULT: token('warn'), soft: token('warn-soft') },
        lvl1: token('lvl1'),
        lvl2: token('lvl2'),
        lvl3: token('lvl3'),
        lvl4: token('lvl4'),
        lvl5: token('lvl5'),
        cat: { logic: token('cat-logic'), strategy: token('cat-strategy'), analytics: token('cat-analytics'), emotional: token('cat-emotional'), memory: token('cat-memory'), academic: token('cat-academic') },
      },
      borderRadius: {
        xl: '14px',
        '2xl': '20px',
        '3xl': '28px',
      },
      boxShadow: {
        card: '0 1px 2px rgb(var(--shadow) / 0.06), 0 8px 24px -12px rgb(var(--shadow) / 0.18)',
        lift: '0 2px 4px rgb(var(--shadow) / 0.06), 0 18px 40px -18px rgb(var(--shadow) / 0.35)',
      },
      keyframes: {
        rise: { from: { opacity: '0', transform: 'translateY(6px)' }, to: { opacity: '1', transform: 'none' } },
        pop: { '0%': { transform: 'scale(0.96)' }, '60%': { transform: 'scale(1.02)' }, '100%': { transform: 'scale(1)' } },
        shake: { '0%,100%': { transform: 'translateX(0)' }, '25%': { transform: 'translateX(-5px)' }, '75%': { transform: 'translateX(5px)' } },
        'fade-up': { from: { opacity: '0', transform: 'translateY(16px)' }, to: { opacity: '1', transform: 'none' } },
        'pop-in': { '0%': { opacity: '0', transform: 'scale(0.6)' }, '70%': { opacity: '1', transform: 'scale(1.08)' }, '100%': { opacity: '1', transform: 'scale(1)' } },
        page: { from: { opacity: '0', transform: 'translateY(10px)' }, to: { opacity: '1', transform: 'none' } },
        float: { '0%,100%': { transform: 'translateY(0) rotate(var(--r, 0deg))' }, '50%': { transform: 'translateY(-14px) rotate(var(--r, 0deg))' } },
        draw: { from: { strokeDashoffset: '40' }, to: { strokeDashoffset: '0' } },
        'xp-float': { '0%': { opacity: '0', transform: 'translateY(6px) scale(0.8)' }, '20%': { opacity: '1', transform: 'translateY(0) scale(1.1)' }, '100%': { opacity: '0', transform: 'translateY(-46px) scale(1)' } },
        burst: {
          '0%': { opacity: '1', transform: 'translate(0, 0) scale(1)' },
          '65%': { opacity: '1' },
          '100%': { opacity: '0', transform: 'translate(var(--dx), var(--dy)) scale(0.5) rotate(var(--rot))' },
        },
        'pulse-soft': { '0%,100%': { boxShadow: '0 0 0 0 rgb(var(--accent) / 0.35)' }, '50%': { boxShadow: '0 0 0 7px rgb(var(--accent) / 0)' } },
        'toast-in': { from: { opacity: '0', transform: 'translate(-50%, -16px) scale(0.96)' }, to: { opacity: '1', transform: 'translate(-50%, 0) scale(1)' } },
        flicker: { '0%,100%': { transform: 'scale(1) rotate(0deg)' }, '30%': { transform: 'scale(1.12) rotate(-6deg)' }, '60%': { transform: 'scale(0.95) rotate(4deg)' } },
        shine: { to: { backgroundPosition: '200% center' } },
        glow: { '0%': { boxShadow: '0 0 0 0 rgb(var(--good) / 0.45)' }, '100%': { boxShadow: '0 0 0 14px rgb(var(--good) / 0)' } },
      },
      animation: {
        rise: 'rise 260ms cubic-bezier(0.22, 1, 0.36, 1)',
        pop: 'pop 320ms cubic-bezier(0.22, 1, 0.36, 1)',
        shake: 'shake 260ms ease-in-out',
        'fade-up': 'fade-up 620ms cubic-bezier(0.22, 1, 0.36, 1) backwards',
        'pop-in': 'pop-in 420ms cubic-bezier(0.22, 1, 0.36, 1) backwards',
        // Появление и затем мягкая пульсация — для клетки со знаком вопроса.
        'pop-pulse': 'pop-in 420ms cubic-bezier(0.22, 1, 0.36, 1) backwards, pulse-soft 1.8s ease-in-out 700ms infinite',
        page: 'page 380ms cubic-bezier(0.22, 1, 0.36, 1) backwards',
        float: 'float 7s ease-in-out infinite',
        draw: 'draw 900ms cubic-bezier(0.22, 1, 0.36, 1) 150ms backwards',
        'xp-float': 'xp-float 1400ms cubic-bezier(0.22, 1, 0.36, 1) both',
        burst: 'burst 1100ms cubic-bezier(0.16, 1, 0.3, 1) both',
        'pulse-soft': 'pulse-soft 1.8s ease-in-out infinite',
        'toast-in': 'toast-in 420ms cubic-bezier(0.22, 1, 0.36, 1) both',
        flicker: 'flicker 1.6s ease-in-out 2',
        glow: 'glow 700ms ease-out',
        shine: 'shine 6s linear infinite',
      },
    },
  },
  plugins: [],
}
